packages:
  - packages/cli/*
  - packages/web/*
  - packages/web/git-dashboard
  - packages/web/package-visualizer
  - packages/web/package-visualizer/client
  - packages/web/package-visualizer/server
  - packages/web/package-visualizer/vscode-extension

hoist: false
hoistWorkspacePackages: false

preferWorkspacePackages: true

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@grasdouble/*'

onlyBuiltDependencies:
  - '@vscode/vsce-sign'
  - esbuild
  - keytar
